### ISSUE TITLE
Search functionality for database

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/law-reading-robot-data#6]
Database should be searchable by the end-user. The front-end will need to develop a search interface, but the backend will need to implement the search for that.

For now, being able to search by the primary identifiers (the ID of the bill, the legislative session, and revision id) will be sufficient, but this will likely need to be updated later.

**Comment by wkbraid** [comment]
The database should handle basic searching by field. I'll open a new issue focused on tag-based searching.
