### ISSUE TITLE
Wrapper functions for backend-database interface

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/law-reading-robot-data#8]
Because the database design is currently in flux, and may be changed at a later point, we probably want to make sure we have a common interface for getting, adding, and updating data from the database that doesn't depend on the particular implementation of the database. 

What I'm thinking is: we need a module, called something like `db_interface.py`, that contains functions corresponding to what we want the database to do (get data, update data, add data, etc.), and accepts parameters that are then interpreted for the particular implementation. The contents of the functions don't matter right now, and can all be blank at this juncture.

What's important is that, if someone wants to get from the database all bills passed in 2021 that begin with the letter "B", they can request that in a Python script without having to worry about SQL or particular function calls, trusting that someone else will design a way to interpret that request.

Ideally, these are a small amount of generalizable functions, so that if we need to change the database implementation, we don't have to change much. 

In my vision of this, this would involve dictionaries: dictionaries for defining table and column names, dictionaries for any relevant WHERE conditions, and lists of dictionaries returned where the key-value pairs correspond to the column-value of the particular row(s) being returned, to be both returned by a SELECT function and passed to an INSERT or UPDATE function.

If people have other ideas for how this could be implemented, or think that using an interface like this is redundant or unnecessary, we can chat about that.

**Comment by wkbraid** [comment]
Minimizing the overlap between functionality and database access is a great idea in general 😄 

I think is this is currently well covered by the supabase python client library, at least for now: https://supabase.com/docs/reference/python/introduction
